export {
  InputLabel,
  Button,
  type ButtonProps,
  Box,
  Tabs,
  type TabsProps,
  Tab,
  Radio,
  type RadioProps,
  RadioGroup,
  type RadioGroupProps,
  FormControl,
  FormGroup,
  TextField,
  type TextFieldProps,
  MenuItem,
  Select,
  type SelectChangeEvent,
  type SelectProps,
  Table,
  TableBody,
  TableCell,
  TableRow,
  TableHead,
  TableContainer,
} from '@mui/material';
